services:
  yt_video_updater_processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    container_name: yt_video_updater_processor
    restart: unless-stopped
    tty: true
    ports:
      - "2003:2003"
    volumes:
      - ./processor:/usr/src/app/yt-video-updater/processor
      - ./processor/package.json:/usr/src/app/yt-video-updater/processor/package.json
      - ./processor/package-lock.json:/usr/src/app/yt-video-updater/processor/package-lock.json
      - /usr/src/app/yt-video-updater/processor/node_modules
    networks:
      - network

  yt_video_updater_puller:
    build:
      context: ./puller
      dockerfile: Dockerfile
    container_name: yt_video_updater_puller
    restart: unless-stopped
    tty: true
    env_file:
      - ./puller/.env
    ports:
      - "5002:5002"
    volumes:
      - ./puller:/var/www/puller
      - ./.docker/php/local.ini:/usr/local/etc/php/local.ini
    networks:
      - network

networks:
  network:
    driver: bridge
